// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/appcontrol.proto

// AppControl is the LOCAL IPC between the WINGS V host app and the embedded
// vk-turn-proxy client (libclient.so), served over a unix domain socket. It
// replaces the older stdin/stdout/cookie-file channels with a typed contract:
// the app pushes VK webview cookies in, and pulls the provisioned WireGuard
// config out.

package appcontrolpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ConfigureRequest mirrors the former CLI flags (clientOptions). Empty/zero
// fields fall back to the relay's own defaults, matching the old flag behaviour.
type ConfigureRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DnsMode          string                 `protobuf:"bytes,1,opt,name=dns_mode,json=dnsMode,proto3" json:"dns_mode,omitempty"`                                  // -dns
	UserDns          string                 `protobuf:"bytes,2,opt,name=user_dns,json=userDns,proto3" json:"user_dns,omitempty"`                                  // -user-dns
	Peer             string                 `protobuf:"bytes,3,opt,name=peer,proto3" json:"peer,omitempty"`                                                       // -peer (VK TURN endpoint)
	VkLink           string                 `protobuf:"bytes,4,opt,name=vk_link,json=vkLink,proto3" json:"vk_link,omitempty"`                                     // -vk-link (comma-joined)
	VkLinkSecondary  string                 `protobuf:"bytes,5,opt,name=vk_link_secondary,json=vkLinkSecondary,proto3" json:"vk_link_secondary,omitempty"`        // -vk-link-secondary
	Listen           string                 `protobuf:"bytes,6,opt,name=listen,proto3" json:"listen,omitempty"`                                                   // -listen (local relay endpoint)
	Threads          int32                  `protobuf:"varint,7,opt,name=threads,proto3" json:"threads,omitempty"`                                                // -n
	CredsGroupSize   int32                  `protobuf:"varint,8,opt,name=creds_group_size,json=credsGroupSize,proto3" json:"creds_group_size,omitempty"`          // -creds-group-size
	Transport        string                 `protobuf:"bytes,9,opt,name=transport,proto3" json:"transport,omitempty"`                                             // -transport (e.g. tcp)
	Udp              bool                   `protobuf:"varint,10,opt,name=udp,proto3" json:"udp,omitempty"`                                                       // -udp
	NoDtls           bool                   `protobuf:"varint,11,opt,name=no_dtls,json=noDtls,proto3" json:"no_dtls,omitempty"`                                   // -no-dtls
	ManualCaptcha    bool                   `protobuf:"varint,12,opt,name=manual_captcha,json=manualCaptcha,proto3" json:"manual_captcha,omitempty"`              // -manual-captcha
	CaptchaSolver    string                 `protobuf:"bytes,13,opt,name=captcha_solver,json=captchaSolver,proto3" json:"captcha_solver,omitempty"`               // -captcha-solver
	VkAuth           string                 `protobuf:"bytes,14,opt,name=vk_auth,json=vkAuth,proto3" json:"vk_auth,omitempty"`                                    // -vk-auth (e.g. account)
	VkSessionFile    string                 `protobuf:"bytes,15,opt,name=vk_session_file,json=vkSessionFile,proto3" json:"vk_session_file,omitempty"`             // -vk-session-file
	VkCookieFilePoll bool                   `protobuf:"varint,16,opt,name=vk_cookie_file_poll,json=vkCookieFilePoll,proto3" json:"vk_cookie_file_poll,omitempty"` // -vk-cookie-file-poll
	SessionMode      string                 `protobuf:"bytes,17,opt,name=session_mode,json=sessionMode,proto3" json:"session_mode,omitempty"`                     // -session-mode
	BrowserFp        string                 `protobuf:"bytes,18,opt,name=browser_fp,json=browserFp,proto3" json:"browser_fp,omitempty"`                           // -browser-fp
	TurnHost         string                 `protobuf:"bytes,19,opt,name=turn_host,json=turnHost,proto3" json:"turn_host,omitempty"`                              // -turn
	TurnPort         string                 `protobuf:"bytes,20,opt,name=turn_port,json=turnPort,proto3" json:"turn_port,omitempty"`                              // -port
	ProtectSock      string                 `protobuf:"bytes,21,opt,name=protect_sock,json=protectSock,proto3" json:"protect_sock,omitempty"`                     // -protect-sock
	WrapMode         string                 `protobuf:"bytes,22,opt,name=wrap_mode,json=wrapMode,proto3" json:"wrap_mode,omitempty"`                              // -wrap-mode
	WrapCipher       string                 `protobuf:"bytes,23,opt,name=wrap_cipher,json=wrapCipher,proto3" json:"wrap_cipher,omitempty"`                        // -wrap-cipher
	WrapKeyHex       string                 `protobuf:"bytes,24,opt,name=wrap_key_hex,json=wrapKeyHex,proto3" json:"wrap_key_hex,omitempty"`                      // -wrap-key
	WrapSendKey      bool                   `protobuf:"varint,25,opt,name=wrap_send_key,json=wrapSendKey,proto3" json:"wrap_send_key,omitempty"`                  // -wrap-send-key
	ProtoFp          string                 `protobuf:"bytes,26,opt,name=proto_fp,json=protoFp,proto3" json:"proto_fp,omitempty"`                                 // -proto-fp
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConfigureRequest) Reset() {
	*x = ConfigureRequest{}
	mi := &file_proto_appcontrol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest) ProtoMessage() {}

func (x *ConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appcontrol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest.ProtoReflect.Descriptor instead.
func (*ConfigureRequest) Descriptor() ([]byte, []int) {
	return file_proto_appcontrol_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigureRequest) GetDnsMode() string {
	if x != nil {
		return x.DnsMode
	}
	return ""
}

func (x *ConfigureRequest) GetUserDns() string {
	if x != nil {
		return x.UserDns
	}
	return ""
}

func (x *ConfigureRequest) GetPeer() string {
	if x != nil {
		return x.Peer
	}
	return ""
}

func (x *ConfigureRequest) GetVkLink() string {
	if x != nil {
		return x.VkLink
	}
	return ""
}

func (x *ConfigureRequest) GetVkLinkSecondary() string {
	if x != nil {
		return x.VkLinkSecondary
	}
	return ""
}

func (x *ConfigureRequest) GetListen() string {
	if x != nil {
		return x.Listen
	}
	return ""
}

func (x *ConfigureRequest) GetThreads() int32 {
	if x != nil {
		return x.Threads
	}
	return 0
}

func (x *ConfigureRequest) GetCredsGroupSize() int32 {
	if x != nil {
		return x.CredsGroupSize
	}
	return 0
}

func (x *ConfigureRequest) GetTransport() string {
	if x != nil {
		return x.Transport
	}
	return ""
}

func (x *ConfigureRequest) GetUdp() bool {
	if x != nil {
		return x.Udp
	}
	return false
}

func (x *ConfigureRequest) GetNoDtls() bool {
	if x != nil {
		return x.NoDtls
	}
	return false
}

func (x *ConfigureRequest) GetManualCaptcha() bool {
	if x != nil {
		return x.ManualCaptcha
	}
	return false
}

func (x *ConfigureRequest) GetCaptchaSolver() string {
	if x != nil {
		return x.CaptchaSolver
	}
	return ""
}

func (x *ConfigureRequest) GetVkAuth() string {
	if x != nil {
		return x.VkAuth
	}
	return ""
}

func (x *ConfigureRequest) GetVkSessionFile() string {
	if x != nil {
		return x.VkSessionFile
	}
	return ""
}

func (x *ConfigureRequest) GetVkCookieFilePoll() bool {
	if x != nil {
		return x.VkCookieFilePoll
	}
	return false
}

func (x *ConfigureRequest) GetSessionMode() string {
	if x != nil {
		return x.SessionMode
	}
	return ""
}

func (x *ConfigureRequest) GetBrowserFp() string {
	if x != nil {
		return x.BrowserFp
	}
	return ""
}

func (x *ConfigureRequest) GetTurnHost() string {
	if x != nil {
		return x.TurnHost
	}
	return ""
}

func (x *ConfigureRequest) GetTurnPort() string {
	if x != nil {
		return x.TurnPort
	}
	return ""
}

func (x *ConfigureRequest) GetProtectSock() string {
	if x != nil {
		return x.ProtectSock
	}
	return ""
}

func (x *ConfigureRequest) GetWrapMode() string {
	if x != nil {
		return x.WrapMode
	}
	return ""
}

func (x *ConfigureRequest) GetWrapCipher() string {
	if x != nil {
		return x.WrapCipher
	}
	return ""
}

func (x *ConfigureRequest) GetWrapKeyHex() string {
	if x != nil {
		return x.WrapKeyHex
	}
	return ""
}

func (x *ConfigureRequest) GetWrapSendKey() bool {
	if x != nil {
		return x.WrapSendKey
	}
	return false
}

func (x *ConfigureRequest) GetProtoFp() string {
	if x != nil {
		return x.ProtoFp
	}
	return ""
}

type ConfigureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureResponse) Reset() {
	*x = ConfigureResponse{}
	mi := &file_proto_appcontrol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureResponse) ProtoMessage() {}

func (x *ConfigureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appcontrol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureResponse.ProtoReflect.Descriptor instead.
func (*ConfigureResponse) Descriptor() ([]byte, []int) {
	return file_proto_appcontrol_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigureResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SetVKCookiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cookies       string                 `protobuf:"bytes,1,opt,name=cookies,proto3" json:"cookies,omitempty"`
	UserAgent     string                 `protobuf:"bytes,2,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetVKCookiesRequest) Reset() {
	*x = SetVKCookiesRequest{}
	mi := &file_proto_appcontrol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetVKCookiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetVKCookiesRequest) ProtoMessage() {}

func (x *SetVKCookiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appcontrol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetVKCookiesRequest.ProtoReflect.Descriptor instead.
func (*SetVKCookiesRequest) Descriptor() ([]byte, []int) {
	return file_proto_appcontrol_proto_rawDescGZIP(), []int{2}
}

func (x *SetVKCookiesRequest) GetCookies() string {
	if x != nil {
		return x.Cookies
	}
	return ""
}

func (x *SetVKCookiesRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

type SetVKCookiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetVKCookiesResponse) Reset() {
	*x = SetVKCookiesResponse{}
	mi := &file_proto_appcontrol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetVKCookiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetVKCookiesResponse) ProtoMessage() {}

func (x *SetVKCookiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appcontrol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetVKCookiesResponse.ProtoReflect.Descriptor instead.
func (*SetVKCookiesResponse) Descriptor() ([]byte, []int) {
	return file_proto_appcontrol_proto_rawDescGZIP(), []int{3}
}

type GetVKCookiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVKCookiesRequest) Reset() {
	*x = GetVKCookiesRequest{}
	mi := &file_proto_appcontrol_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVKCookiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVKCookiesRequest) ProtoMessage() {}

func (x *GetVKCookiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appcontrol_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVKCookiesRequest.ProtoReflect.Descriptor instead.
func (*GetVKCookiesRequest) Descriptor() ([]byte, []int) {
	return file_proto_appcontrol_proto_rawDescGZIP(), []int{4}
}

type GetVKCookiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cookies       string                 `protobuf:"bytes,1,opt,name=cookies,proto3" json:"cookies,omitempty"`
	UserAgent     string                 `protobuf:"bytes,2,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVKCookiesResponse) Reset() {
	*x = GetVKCookiesResponse{}
	mi := &file_proto_appcontrol_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVKCookiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVKCookiesResponse) ProtoMessage() {}

func (x *GetVKCookiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appcontrol_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVKCookiesResponse.ProtoReflect.Descriptor instead.
func (*GetVKCookiesResponse) Descriptor() ([]byte, []int) {
	return file_proto_appcontrol_proto_rawDescGZIP(), []int{5}
}

func (x *GetVKCookiesResponse) GetCookies() string {
	if x != nil {
		return x.Cookies
	}
	return ""
}

func (x *GetVKCookiesResponse) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

type ProvisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Token         []byte                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Hwid          string                 `protobuf:"bytes,3,opt,name=hwid,proto3" json:"hwid,omitempty"`
	LocalPort     uint32                 `protobuf:"varint,4,opt,name=local_port,json=localPort,proto3" json:"local_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionRequest) Reset() {
	*x = ProvisionRequest{}
	mi := &file_proto_appcontrol_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionRequest) ProtoMessage() {}

func (x *ProvisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appcontrol_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionRequest.ProtoReflect.Descriptor instead.
func (*ProvisionRequest) Descriptor() ([]byte, []int) {
	return file_proto_appcontrol_proto_rawDescGZIP(), []int{6}
}

func (x *ProvisionRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ProvisionRequest) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *ProvisionRequest) GetHwid() string {
	if x != nil {
		return x.Hwid
	}
	return ""
}

func (x *ProvisionRequest) GetLocalPort() uint32 {
	if x != nil {
		return x.LocalPort
	}
	return 0
}

type ProvisionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wg            *WireguardConfig       `protobuf:"bytes,1,opt,name=wg,proto3" json:"wg,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionResponse) Reset() {
	*x = ProvisionResponse{}
	mi := &file_proto_appcontrol_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionResponse) ProtoMessage() {}

func (x *ProvisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appcontrol_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionResponse.ProtoReflect.Descriptor instead.
func (*ProvisionResponse) Descriptor() ([]byte, []int) {
	return file_proto_appcontrol_proto_rawDescGZIP(), []int{7}
}

func (x *ProvisionResponse) GetWg() *WireguardConfig {
	if x != nil {
		return x.Wg
	}
	return nil
}

func (x *ProvisionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetTelemetryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTelemetryRequest) Reset() {
	*x = GetTelemetryRequest{}
	mi := &file_proto_appcontrol_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTelemetryRequest) ProtoMessage() {}

func (x *GetTelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appcontrol_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTelemetryRequest.ProtoReflect.Descriptor instead.
func (*GetTelemetryRequest) Descriptor() ([]byte, []int) {
	return file_proto_appcontrol_proto_rawDescGZIP(), []int{8}
}

type StreamTelemetryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamTelemetryRequest) Reset() {
	*x = StreamTelemetryRequest{}
	mi := &file_proto_appcontrol_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamTelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamTelemetryRequest) ProtoMessage() {}

func (x *StreamTelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appcontrol_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamTelemetryRequest.ProtoReflect.Descriptor instead.
func (*StreamTelemetryRequest) Descriptor() ([]byte, []int) {
	return file_proto_appcontrol_proto_rawDescGZIP(), []int{9}
}

type Telemetry struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ConnectedStreams int64                  `protobuf:"varint,1,opt,name=connected_streams,json=connectedStreams,proto3" json:"connected_streams,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Telemetry) Reset() {
	*x = Telemetry{}
	mi := &file_proto_appcontrol_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Telemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Telemetry) ProtoMessage() {}

func (x *Telemetry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appcontrol_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Telemetry.ProtoReflect.Descriptor instead.
func (*Telemetry) Descriptor() ([]byte, []int) {
	return file_proto_appcontrol_proto_rawDescGZIP(), []int{10}
}

func (x *Telemetry) GetConnectedStreams() int64 {
	if x != nil {
		return x.ConnectedStreams
	}
	return 0
}

type StreamEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_proto_appcontrol_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appcontrol_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_appcontrol_proto_rawDescGZIP(), []int{11}
}

// ProxyEvent is one relay control event. It carries exactly one of the variants
// below - the same information the relay prints as a PROXY_EVENT JSONL line.
type ProxyEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ProxyEvent_Status
	//	*ProxyEvent_Caps
	//	*ProxyEvent_Captcha
	//	*ProxyEvent_Lockout
	//	*ProxyEvent_VkAccountAuth
	//	*ProxyEvent_VkCookiesRequired
	Event         isProxyEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyEvent) Reset() {
	*x = ProxyEvent{}
	mi := &file_proto_appcontrol_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyEvent) ProtoMessage() {}

func (x *ProxyEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appcontrol_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyEvent.ProtoReflect.Descriptor instead.
func (*ProxyEvent) Descriptor() ([]byte, []int) {
	return file_proto_appcontrol_proto_rawDescGZIP(), []int{12}
}

func (x *ProxyEvent) GetEvent() isProxyEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ProxyEvent) GetStatus() *StatusEvent {
	if x != nil {
		if x, ok := x.Event.(*ProxyEvent_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *ProxyEvent) GetCaps() *CapsEvent {
	if x != nil {
		if x, ok := x.Event.(*ProxyEvent_Caps); ok {
			return x.Caps
		}
	}
	return nil
}

func (x *ProxyEvent) GetCaptcha() *CaptchaEvent {
	if x != nil {
		if x, ok := x.Event.(*ProxyEvent_Captcha); ok {
			return x.Captcha
		}
	}
	return nil
}

func (x *ProxyEvent) GetLockout() *LockoutEvent {
	if x != nil {
		if x, ok := x.Event.(*ProxyEvent_Lockout); ok {
			return x.Lockout
		}
	}
	return nil
}

func (x *ProxyEvent) GetVkAccountAuth() *VKAccountAuthEvent {
	if x != nil {
		if x, ok := x.Event.(*ProxyEvent_VkAccountAuth); ok {
			return x.VkAccountAuth
		}
	}
	return nil
}

func (x *ProxyEvent) GetVkCookiesRequired() *VKCookiesRequiredEvent {
	if x != nil {
		if x, ok := x.Event.(*ProxyEvent_VkCookiesRequired); ok {
			return x.VkCookiesRequired
		}
	}
	return nil
}

type isProxyEvent_Event interface {
	isProxyEvent_Event()
}

type ProxyEvent_Status struct {
	Status *StatusEvent `protobuf:"bytes,1,opt,name=status,proto3,oneof"`
}

type ProxyEvent_Caps struct {
	Caps *CapsEvent `protobuf:"bytes,2,opt,name=caps,proto3,oneof"`
}

type ProxyEvent_Captcha struct {
	Captcha *CaptchaEvent `protobuf:"bytes,3,opt,name=captcha,proto3,oneof"`
}

type ProxyEvent_Lockout struct {
	Lockout *LockoutEvent `protobuf:"bytes,4,opt,name=lockout,proto3,oneof"`
}

type ProxyEvent_VkAccountAuth struct {
	VkAccountAuth *VKAccountAuthEvent `protobuf:"bytes,5,opt,name=vk_account_auth,json=vkAccountAuth,proto3,oneof"`
}

type ProxyEvent_VkCookiesRequired struct {
	VkCookiesRequired *VKCookiesRequiredEvent `protobuf:"bytes,6,opt,name=vk_cookies_required,json=vkCookiesRequired,proto3,oneof"`
}

func (*ProxyEvent_Status) isProxyEvent_Event() {}

func (*ProxyEvent_Caps) isProxyEvent_Event() {}

func (*ProxyEvent_Captcha) isProxyEvent_Event() {}

func (*ProxyEvent_Lockout) isProxyEvent_Event() {}

func (*ProxyEvent_VkAccountAuth) isProxyEvent_Event() {}

func (*ProxyEvent_VkCookiesRequired) isProxyEvent_Event() {}

// StatusEvent reports a connection-progress phase (auth_ready, turn_ready,
// dtls_ready, dtls_alive, ...). stream_id attributes it to a TURN stream (0 for
// process-wide phases); connected_streams is the live count carried by the
// dtls_alive heartbeat (0 when not reported).
type StatusEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Phase            string                 `protobuf:"bytes,1,opt,name=phase,proto3" json:"phase,omitempty"`
	StreamId         int32                  `protobuf:"varint,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	ConnectedStreams int32                  `protobuf:"varint,3,opt,name=connected_streams,json=connectedStreams,proto3" json:"connected_streams,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StatusEvent) Reset() {
	*x = StatusEvent{}
	mi := &file_proto_appcontrol_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusEvent) ProtoMessage() {}

func (x *StatusEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appcontrol_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusEvent.ProtoReflect.Descriptor instead.
func (*StatusEvent) Descriptor() ([]byte, []int) {
	return file_proto_appcontrol_proto_rawDescGZIP(), []int{13}
}

func (x *StatusEvent) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *StatusEvent) GetStreamId() int32 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

func (x *StatusEvent) GetConnectedStreams() int32 {
	if x != nil {
		return x.ConnectedStreams
	}
	return 0
}

// CapsEvent advertises the relay event-protocol version and capability tokens.
type CapsEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int32                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Capabilities  []string               `protobuf:"bytes,2,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapsEvent) Reset() {
	*x = CapsEvent{}
	mi := &file_proto_appcontrol_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapsEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapsEvent) ProtoMessage() {}

func (x *CapsEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appcontrol_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapsEvent.ProtoReflect.Descriptor instead.
func (*CapsEvent) Descriptor() ([]byte, []int) {
	return file_proto_appcontrol_proto_rawDescGZIP(), []int{14}
}

func (x *CapsEvent) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *CapsEvent) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// CaptchaEvent mirrors the PROXY_EVENT captcha payload. state is one of
// required|pending|solving|solved|cancelled|expired; source is primary|pool; url
// and user_agent are set for required/pending prompts.
type CaptchaEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	UserAgent     string                 `protobuf:"bytes,4,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptchaEvent) Reset() {
	*x = CaptchaEvent{}
	mi := &file_proto_appcontrol_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptchaEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptchaEvent) ProtoMessage() {}

func (x *CaptchaEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appcontrol_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptchaEvent.ProtoReflect.Descriptor instead.
func (*CaptchaEvent) Descriptor() ([]byte, []int) {
	return file_proto_appcontrol_proto_rawDescGZIP(), []int{15}
}

func (x *CaptchaEvent) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *CaptchaEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CaptchaEvent) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CaptchaEvent) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

// LockoutEvent reports how long VK has locked out captcha attempts.
type LockoutEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seconds       int32                  `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockoutEvent) Reset() {
	*x = LockoutEvent{}
	mi := &file_proto_appcontrol_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockoutEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockoutEvent) ProtoMessage() {}

func (x *LockoutEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appcontrol_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockoutEvent.ProtoReflect.Descriptor instead.
func (*LockoutEvent) Descriptor() ([]byte, []int) {
	return file_proto_appcontrol_proto_rawDescGZIP(), []int{16}
}

func (x *LockoutEvent) GetSeconds() int32 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

// VKAccountAuthEvent drives the VK account sign-in WebView. phase is
// required|complete|failed; link is the VK join URL (required); reason is the
// failure detail (failed).
type VKAccountAuthEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phase         string                 `protobuf:"bytes,1,opt,name=phase,proto3" json:"phase,omitempty"`
	Link          string                 `protobuf:"bytes,2,opt,name=link,proto3" json:"link,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VKAccountAuthEvent) Reset() {
	*x = VKAccountAuthEvent{}
	mi := &file_proto_appcontrol_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VKAccountAuthEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VKAccountAuthEvent) ProtoMessage() {}

func (x *VKAccountAuthEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appcontrol_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VKAccountAuthEvent.ProtoReflect.Descriptor instead.
func (*VKAccountAuthEvent) Descriptor() ([]byte, []int) {
	return file_proto_appcontrol_proto_rawDescGZIP(), []int{17}
}

func (x *VKAccountAuthEvent) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *VKAccountAuthEvent) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *VKAccountAuthEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// VKCookiesRequiredEvent asks the app to (re)deliver the VK web session so the
// relay can mint a privileged TURN token.
type VKCookiesRequiredEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VKCookiesRequiredEvent) Reset() {
	*x = VKCookiesRequiredEvent{}
	mi := &file_proto_appcontrol_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VKCookiesRequiredEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VKCookiesRequiredEvent) ProtoMessage() {}

func (x *VKCookiesRequiredEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appcontrol_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VKCookiesRequiredEvent.ProtoReflect.Descriptor instead.
func (*VKCookiesRequiredEvent) Descriptor() ([]byte, []int) {
	return file_proto_appcontrol_proto_rawDescGZIP(), []int{18}
}

type VKAccountCredsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          string                 `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Credential    string                 `protobuf:"bytes,3,opt,name=credential,proto3" json:"credential,omitempty"`
	TurnUrls      []string               `protobuf:"bytes,4,rep,name=turn_urls,json=turnUrls,proto3" json:"turn_urls,omitempty"`
	Cancel        bool                   `protobuf:"varint,5,opt,name=cancel,proto3" json:"cancel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VKAccountCredsRequest) Reset() {
	*x = VKAccountCredsRequest{}
	mi := &file_proto_appcontrol_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VKAccountCredsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VKAccountCredsRequest) ProtoMessage() {}

func (x *VKAccountCredsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appcontrol_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VKAccountCredsRequest.ProtoReflect.Descriptor instead.
func (*VKAccountCredsRequest) Descriptor() ([]byte, []int) {
	return file_proto_appcontrol_proto_rawDescGZIP(), []int{19}
}

func (x *VKAccountCredsRequest) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *VKAccountCredsRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *VKAccountCredsRequest) GetCredential() string {
	if x != nil {
		return x.Credential
	}
	return ""
}

func (x *VKAccountCredsRequest) GetTurnUrls() []string {
	if x != nil {
		return x.TurnUrls
	}
	return nil
}

func (x *VKAccountCredsRequest) GetCancel() bool {
	if x != nil {
		return x.Cancel
	}
	return false
}

type VKAccountCredsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VKAccountCredsResponse) Reset() {
	*x = VKAccountCredsResponse{}
	mi := &file_proto_appcontrol_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VKAccountCredsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VKAccountCredsResponse) ProtoMessage() {}

func (x *VKAccountCredsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appcontrol_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VKAccountCredsResponse.ProtoReflect.Descriptor instead.
func (*VKAccountCredsResponse) Descriptor() ([]byte, []int) {
	return file_proto_appcontrol_proto_rawDescGZIP(), []int{20}
}

type WireguardConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PrivateKey      string                 `protobuf:"bytes,1,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	PublicKey       string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Address         string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	ServerPublicKey string                 `protobuf:"bytes,4,opt,name=server_public_key,json=serverPublicKey,proto3" json:"server_public_key,omitempty"`
	AllowedIps      string                 `protobuf:"bytes,5,opt,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`
	Mtu             uint32                 `protobuf:"varint,6,opt,name=mtu,proto3" json:"mtu,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WireguardConfig) Reset() {
	*x = WireguardConfig{}
	mi := &file_proto_appcontrol_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireguardConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireguardConfig) ProtoMessage() {}

func (x *WireguardConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appcontrol_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireguardConfig.ProtoReflect.Descriptor instead.
func (*WireguardConfig) Descriptor() ([]byte, []int) {
	return file_proto_appcontrol_proto_rawDescGZIP(), []int{21}
}

func (x *WireguardConfig) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *WireguardConfig) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *WireguardConfig) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *WireguardConfig) GetServerPublicKey() string {
	if x != nil {
		return x.ServerPublicKey
	}
	return ""
}

func (x *WireguardConfig) GetAllowedIps() string {
	if x != nil {
		return x.AllowedIps
	}
	return ""
}

func (x *WireguardConfig) GetMtu() uint32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

var File_proto_appcontrol_proto protoreflect.FileDescriptor

const file_proto_appcontrol_proto_rawDesc = "" +
	"\n" +
	"\x16proto/appcontrol.proto\x12\x14vkturn.appcontrol.v1\"\xc2\x06\n" +
	"\x10ConfigureRequest\x12\x19\n" +
	"\bdns_mode\x18\x01 \x01(\tR\adnsMode\x12\x19\n" +
	"\buser_dns\x18\x02 \x01(\tR\auserDns\x12\x12\n" +
	"\x04peer\x18\x03 \x01(\tR\x04peer\x12\x17\n" +
	"\avk_link\x18\x04 \x01(\tR\x06vkLink\x12*\n" +
	"\x11vk_link_secondary\x18\x05 \x01(\tR\x0fvkLinkSecondary\x12\x16\n" +
	"\x06listen\x18\x06 \x01(\tR\x06listen\x12\x18\n" +
	"\athreads\x18\a \x01(\x05R\athreads\x12(\n" +
	"\x10creds_group_size\x18\b \x01(\x05R\x0ecredsGroupSize\x12\x1c\n" +
	"\ttransport\x18\t \x01(\tR\ttransport\x12\x10\n" +
	"\x03udp\x18\n" +
	" \x01(\bR\x03udp\x12\x17\n" +
	"\ano_dtls\x18\v \x01(\bR\x06noDtls\x12%\n" +
	"\x0emanual_captcha\x18\f \x01(\bR\rmanualCaptcha\x12%\n" +
	"\x0ecaptcha_solver\x18\r \x01(\tR\rcaptchaSolver\x12\x17\n" +
	"\avk_auth\x18\x0e \x01(\tR\x06vkAuth\x12&\n" +
	"\x0fvk_session_file\x18\x0f \x01(\tR\rvkSessionFile\x12-\n" +
	"\x13vk_cookie_file_poll\x18\x10 \x01(\bR\x10vkCookieFilePoll\x12!\n" +
	"\fsession_mode\x18\x11 \x01(\tR\vsessionMode\x12\x1d\n" +
	"\n" +
	"browser_fp\x18\x12 \x01(\tR\tbrowserFp\x12\x1b\n" +
	"\tturn_host\x18\x13 \x01(\tR\bturnHost\x12\x1b\n" +
	"\tturn_port\x18\x14 \x01(\tR\bturnPort\x12!\n" +
	"\fprotect_sock\x18\x15 \x01(\tR\vprotectSock\x12\x1b\n" +
	"\twrap_mode\x18\x16 \x01(\tR\bwrapMode\x12\x1f\n" +
	"\vwrap_cipher\x18\x17 \x01(\tR\n" +
	"wrapCipher\x12 \n" +
	"\fwrap_key_hex\x18\x18 \x01(\tR\n" +
	"wrapKeyHex\x12\"\n" +
	"\rwrap_send_key\x18\x19 \x01(\bR\vwrapSendKey\x12\x19\n" +
	"\bproto_fp\x18\x1a \x01(\tR\aprotoFp\")\n" +
	"\x11ConfigureResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"N\n" +
	"\x13SetVKCookiesRequest\x12\x18\n" +
	"\acookies\x18\x01 \x01(\tR\acookies\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x02 \x01(\tR\tuserAgent\"\x16\n" +
	"\x14SetVKCookiesResponse\"\x15\n" +
	"\x13GetVKCookiesRequest\"O\n" +
	"\x14GetVKCookiesResponse\x12\x18\n" +
	"\acookies\x18\x01 \x01(\tR\acookies\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x02 \x01(\tR\tuserAgent\"x\n" +
	"\x10ProvisionRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\fR\x05token\x12\x12\n" +
	"\x04hwid\x18\x03 \x01(\tR\x04hwid\x12\x1d\n" +
	"\n" +
	"local_port\x18\x04 \x01(\rR\tlocalPort\"`\n" +
	"\x11ProvisionResponse\x125\n" +
	"\x02wg\x18\x01 \x01(\v2%.vkturn.appcontrol.v1.WireguardConfigR\x02wg\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x15\n" +
	"\x13GetTelemetryRequest\"\x18\n" +
	"\x16StreamTelemetryRequest\"8\n" +
	"\tTelemetry\x12+\n" +
	"\x11connected_streams\x18\x01 \x01(\x03R\x10connectedStreams\"\x15\n" +
	"\x13StreamEventsRequest\"\xbd\x03\n" +
	"\n" +
	"ProxyEvent\x12;\n" +
	"\x06status\x18\x01 \x01(\v2!.vkturn.appcontrol.v1.StatusEventH\x00R\x06status\x125\n" +
	"\x04caps\x18\x02 \x01(\v2\x1f.vkturn.appcontrol.v1.CapsEventH\x00R\x04caps\x12>\n" +
	"\acaptcha\x18\x03 \x01(\v2\".vkturn.appcontrol.v1.CaptchaEventH\x00R\acaptcha\x12>\n" +
	"\alockout\x18\x04 \x01(\v2\".vkturn.appcontrol.v1.LockoutEventH\x00R\alockout\x12R\n" +
	"\x0fvk_account_auth\x18\x05 \x01(\v2(.vkturn.appcontrol.v1.VKAccountAuthEventH\x00R\rvkAccountAuth\x12^\n" +
	"\x13vk_cookies_required\x18\x06 \x01(\v2,.vkturn.appcontrol.v1.VKCookiesRequiredEventH\x00R\x11vkCookiesRequiredB\a\n" +
	"\x05event\"m\n" +
	"\vStatusEvent\x12\x14\n" +
	"\x05phase\x18\x01 \x01(\tR\x05phase\x12\x1b\n" +
	"\tstream_id\x18\x02 \x01(\x05R\bstreamId\x12+\n" +
	"\x11connected_streams\x18\x03 \x01(\x05R\x10connectedStreams\"I\n" +
	"\tCapsEvent\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\x12\"\n" +
	"\fcapabilities\x18\x02 \x03(\tR\fcapabilities\"m\n" +
	"\fCaptchaEvent\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x04 \x01(\tR\tuserAgent\"(\n" +
	"\fLockoutEvent\x12\x18\n" +
	"\aseconds\x18\x01 \x01(\x05R\aseconds\"V\n" +
	"\x12VKAccountAuthEvent\x12\x14\n" +
	"\x05phase\x18\x01 \x01(\tR\x05phase\x12\x12\n" +
	"\x04link\x18\x02 \x01(\tR\x04link\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\x18\n" +
	"\x16VKCookiesRequiredEvent\"\x9c\x01\n" +
	"\x15VKAccountCredsRequest\x12\x12\n" +
	"\x04link\x18\x01 \x01(\tR\x04link\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1e\n" +
	"\n" +
	"credential\x18\x03 \x01(\tR\n" +
	"credential\x12\x1b\n" +
	"\tturn_urls\x18\x04 \x03(\tR\bturnUrls\x12\x16\n" +
	"\x06cancel\x18\x05 \x01(\bR\x06cancel\"\x18\n" +
	"\x16VKAccountCredsResponse\"\xca\x01\n" +
	"\x0fWireguardConfig\x12\x1f\n" +
	"\vprivate_key\x18\x01 \x01(\tR\n" +
	"privateKey\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12*\n" +
	"\x11server_public_key\x18\x04 \x01(\tR\x0fserverPublicKey\x12\x1f\n" +
	"\vallowed_ips\x18\x05 \x01(\tR\n" +
	"allowedIps\x12\x10\n" +
	"\x03mtu\x18\x06 \x01(\rR\x03mtu2\xa8\x06\n" +
	"\n" +
	"AppControl\x12e\n" +
	"\fSetVKCookies\x12).vkturn.appcontrol.v1.SetVKCookiesRequest\x1a*.vkturn.appcontrol.v1.SetVKCookiesResponse\x12e\n" +
	"\fGetVKCookies\x12).vkturn.appcontrol.v1.GetVKCookiesRequest\x1a*.vkturn.appcontrol.v1.GetVKCookiesResponse\x12\\\n" +
	"\tProvision\x12&.vkturn.appcontrol.v1.ProvisionRequest\x1a'.vkturn.appcontrol.v1.ProvisionResponse\x12Z\n" +
	"\fGetTelemetry\x12).vkturn.appcontrol.v1.GetTelemetryRequest\x1a\x1f.vkturn.appcontrol.v1.Telemetry\x12b\n" +
	"\x0fStreamTelemetry\x12,.vkturn.appcontrol.v1.StreamTelemetryRequest\x1a\x1f.vkturn.appcontrol.v1.Telemetry0\x01\x12\\\n" +
	"\tConfigure\x12&.vkturn.appcontrol.v1.ConfigureRequest\x1a'.vkturn.appcontrol.v1.ConfigureResponse\x12]\n" +
	"\fStreamEvents\x12).vkturn.appcontrol.v1.StreamEventsRequest\x1a .vkturn.appcontrol.v1.ProxyEvent0\x01\x12q\n" +
	"\x14SubmitVKAccountCreds\x12+.vkturn.appcontrol.v1.VKAccountCredsRequest\x1a,.vkturn.appcontrol.v1.VKAccountCredsResponseBj\n" +
	"\x18wings.v.proto.appcontrolB\x0fAppControlProtoH\x03Z;github.com/cacggghp/vk-turn-proxy/appcontrolpb;appcontrolpbb\x06proto3"

var (
	file_proto_appcontrol_proto_rawDescOnce sync.Once
	file_proto_appcontrol_proto_rawDescData []byte
)

func file_proto_appcontrol_proto_rawDescGZIP() []byte {
	file_proto_appcontrol_proto_rawDescOnce.Do(func() {
		file_proto_appcontrol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_appcontrol_proto_rawDesc), len(file_proto_appcontrol_proto_rawDesc)))
	})
	return file_proto_appcontrol_proto_rawDescData
}

var file_proto_appcontrol_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_proto_appcontrol_proto_goTypes = []any{
	(*ConfigureRequest)(nil),       // 0: vkturn.appcontrol.v1.ConfigureRequest
	(*ConfigureResponse)(nil),      // 1: vkturn.appcontrol.v1.ConfigureResponse
	(*SetVKCookiesRequest)(nil),    // 2: vkturn.appcontrol.v1.SetVKCookiesRequest
	(*SetVKCookiesResponse)(nil),   // 3: vkturn.appcontrol.v1.SetVKCookiesResponse
	(*GetVKCookiesRequest)(nil),    // 4: vkturn.appcontrol.v1.GetVKCookiesRequest
	(*GetVKCookiesResponse)(nil),   // 5: vkturn.appcontrol.v1.GetVKCookiesResponse
	(*ProvisionRequest)(nil),       // 6: vkturn.appcontrol.v1.ProvisionRequest
	(*ProvisionResponse)(nil),      // 7: vkturn.appcontrol.v1.ProvisionResponse
	(*GetTelemetryRequest)(nil),    // 8: vkturn.appcontrol.v1.GetTelemetryRequest
	(*StreamTelemetryRequest)(nil), // 9: vkturn.appcontrol.v1.StreamTelemetryRequest
	(*Telemetry)(nil),              // 10: vkturn.appcontrol.v1.Telemetry
	(*StreamEventsRequest)(nil),    // 11: vkturn.appcontrol.v1.StreamEventsRequest
	(*ProxyEvent)(nil),             // 12: vkturn.appcontrol.v1.ProxyEvent
	(*StatusEvent)(nil),            // 13: vkturn.appcontrol.v1.StatusEvent
	(*CapsEvent)(nil),              // 14: vkturn.appcontrol.v1.CapsEvent
	(*CaptchaEvent)(nil),           // 15: vkturn.appcontrol.v1.CaptchaEvent
	(*LockoutEvent)(nil),           // 16: vkturn.appcontrol.v1.LockoutEvent
	(*VKAccountAuthEvent)(nil),     // 17: vkturn.appcontrol.v1.VKAccountAuthEvent
	(*VKCookiesRequiredEvent)(nil), // 18: vkturn.appcontrol.v1.VKCookiesRequiredEvent
	(*VKAccountCredsRequest)(nil),  // 19: vkturn.appcontrol.v1.VKAccountCredsRequest
	(*VKAccountCredsResponse)(nil), // 20: vkturn.appcontrol.v1.VKAccountCredsResponse
	(*WireguardConfig)(nil),        // 21: vkturn.appcontrol.v1.WireguardConfig
}
var file_proto_appcontrol_proto_depIdxs = []int32{
	21, // 0: vkturn.appcontrol.v1.ProvisionResponse.wg:type_name -> vkturn.appcontrol.v1.WireguardConfig
	13, // 1: vkturn.appcontrol.v1.ProxyEvent.status:type_name -> vkturn.appcontrol.v1.StatusEvent
	14, // 2: vkturn.appcontrol.v1.ProxyEvent.caps:type_name -> vkturn.appcontrol.v1.CapsEvent
	15, // 3: vkturn.appcontrol.v1.ProxyEvent.captcha:type_name -> vkturn.appcontrol.v1.CaptchaEvent
	16, // 4: vkturn.appcontrol.v1.ProxyEvent.lockout:type_name -> vkturn.appcontrol.v1.LockoutEvent
	17, // 5: vkturn.appcontrol.v1.ProxyEvent.vk_account_auth:type_name -> vkturn.appcontrol.v1.VKAccountAuthEvent
	18, // 6: vkturn.appcontrol.v1.ProxyEvent.vk_cookies_required:type_name -> vkturn.appcontrol.v1.VKCookiesRequiredEvent
	2,  // 7: vkturn.appcontrol.v1.AppControl.SetVKCookies:input_type -> vkturn.appcontrol.v1.SetVKCookiesRequest
	4,  // 8: vkturn.appcontrol.v1.AppControl.GetVKCookies:input_type -> vkturn.appcontrol.v1.GetVKCookiesRequest
	6,  // 9: vkturn.appcontrol.v1.AppControl.Provision:input_type -> vkturn.appcontrol.v1.ProvisionRequest
	8,  // 10: vkturn.appcontrol.v1.AppControl.GetTelemetry:input_type -> vkturn.appcontrol.v1.GetTelemetryRequest
	9,  // 11: vkturn.appcontrol.v1.AppControl.StreamTelemetry:input_type -> vkturn.appcontrol.v1.StreamTelemetryRequest
	0,  // 12: vkturn.appcontrol.v1.AppControl.Configure:input_type -> vkturn.appcontrol.v1.ConfigureRequest
	11, // 13: vkturn.appcontrol.v1.AppControl.StreamEvents:input_type -> vkturn.appcontrol.v1.StreamEventsRequest
	19, // 14: vkturn.appcontrol.v1.AppControl.SubmitVKAccountCreds:input_type -> vkturn.appcontrol.v1.VKAccountCredsRequest
	3,  // 15: vkturn.appcontrol.v1.AppControl.SetVKCookies:output_type -> vkturn.appcontrol.v1.SetVKCookiesResponse
	5,  // 16: vkturn.appcontrol.v1.AppControl.GetVKCookies:output_type -> vkturn.appcontrol.v1.GetVKCookiesResponse
	7,  // 17: vkturn.appcontrol.v1.AppControl.Provision:output_type -> vkturn.appcontrol.v1.ProvisionResponse
	10, // 18: vkturn.appcontrol.v1.AppControl.GetTelemetry:output_type -> vkturn.appcontrol.v1.Telemetry
	10, // 19: vkturn.appcontrol.v1.AppControl.StreamTelemetry:output_type -> vkturn.appcontrol.v1.Telemetry
	1,  // 20: vkturn.appcontrol.v1.AppControl.Configure:output_type -> vkturn.appcontrol.v1.ConfigureResponse
	12, // 21: vkturn.appcontrol.v1.AppControl.StreamEvents:output_type -> vkturn.appcontrol.v1.ProxyEvent
	20, // 22: vkturn.appcontrol.v1.AppControl.SubmitVKAccountCreds:output_type -> vkturn.appcontrol.v1.VKAccountCredsResponse
	15, // [15:23] is the sub-list for method output_type
	7,  // [7:15] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_appcontrol_proto_init() }
func file_proto_appcontrol_proto_init() {
	if File_proto_appcontrol_proto != nil {
		return
	}
	file_proto_appcontrol_proto_msgTypes[12].OneofWrappers = []any{
		(*ProxyEvent_Status)(nil),
		(*ProxyEvent_Caps)(nil),
		(*ProxyEvent_Captcha)(nil),
		(*ProxyEvent_Lockout)(nil),
		(*ProxyEvent_VkAccountAuth)(nil),
		(*ProxyEvent_VkCookiesRequired)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_appcontrol_proto_rawDesc), len(file_proto_appcontrol_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_appcontrol_proto_goTypes,
		DependencyIndexes: file_proto_appcontrol_proto_depIdxs,
		MessageInfos:      file_proto_appcontrol_proto_msgTypes,
	}.Build()
	File_proto_appcontrol_proto = out.File
	file_proto_appcontrol_proto_goTypes = nil
	file_proto_appcontrol_proto_depIdxs = nil
}
