// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.0
// source: proto/appcontrol.proto

// AppControl is the LOCAL IPC between the WINGS V host app and the embedded
// vk-turn-proxy client (libclient.so), served over a unix domain socket. It
// replaces the older stdin/stdout/cookie-file channels with a typed contract:
// the app pushes VK webview cookies in, and pulls the provisioned WireGuard
// config out.

package appcontrolpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AppControl_SetVKCookies_FullMethodName = "/vkturn.appcontrol.v1.AppControl/SetVKCookies"
	AppControl_GetVKCookies_FullMethodName = "/vkturn.appcontrol.v1.AppControl/GetVKCookies"
	AppControl_Provision_FullMethodName    = "/vkturn.appcontrol.v1.AppControl/Provision"
)

// AppControlClient is the client API for AppControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AppControlClient interface {
	SetVKCookies(ctx context.Context, in *SetVKCookiesRequest, opts ...grpc.CallOption) (*SetVKCookiesResponse, error)
	// GetVKCookies lets the app pull the current (possibly relay-rotated) session
	// over gRPC instead of reading a vk_cookies_update line off stdout, so cookies
	// never touch stdout / logcat.
	GetVKCookies(ctx context.Context, in *GetVKCookiesRequest, opts ...grpc.CallOption) (*GetVKCookiesResponse, error)
	Provision(ctx context.Context, in *ProvisionRequest, opts ...grpc.CallOption) (*ProvisionResponse, error)
}

type appControlClient struct {
	cc grpc.ClientConnInterface
}

func NewAppControlClient(cc grpc.ClientConnInterface) AppControlClient {
	return &appControlClient{cc}
}

func (c *appControlClient) SetVKCookies(ctx context.Context, in *SetVKCookiesRequest, opts ...grpc.CallOption) (*SetVKCookiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetVKCookiesResponse)
	err := c.cc.Invoke(ctx, AppControl_SetVKCookies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appControlClient) GetVKCookies(ctx context.Context, in *GetVKCookiesRequest, opts ...grpc.CallOption) (*GetVKCookiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVKCookiesResponse)
	err := c.cc.Invoke(ctx, AppControl_GetVKCookies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appControlClient) Provision(ctx context.Context, in *ProvisionRequest, opts ...grpc.CallOption) (*ProvisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProvisionResponse)
	err := c.cc.Invoke(ctx, AppControl_Provision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppControlServer is the server API for AppControl service.
// All implementations must embed UnimplementedAppControlServer
// for forward compatibility.
type AppControlServer interface {
	SetVKCookies(context.Context, *SetVKCookiesRequest) (*SetVKCookiesResponse, error)
	// GetVKCookies lets the app pull the current (possibly relay-rotated) session
	// over gRPC instead of reading a vk_cookies_update line off stdout, so cookies
	// never touch stdout / logcat.
	GetVKCookies(context.Context, *GetVKCookiesRequest) (*GetVKCookiesResponse, error)
	Provision(context.Context, *ProvisionRequest) (*ProvisionResponse, error)
	mustEmbedUnimplementedAppControlServer()
}

// UnimplementedAppControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAppControlServer struct{}

func (UnimplementedAppControlServer) SetVKCookies(context.Context, *SetVKCookiesRequest) (*SetVKCookiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetVKCookies not implemented")
}
func (UnimplementedAppControlServer) GetVKCookies(context.Context, *GetVKCookiesRequest) (*GetVKCookiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVKCookies not implemented")
}
func (UnimplementedAppControlServer) Provision(context.Context, *ProvisionRequest) (*ProvisionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Provision not implemented")
}
func (UnimplementedAppControlServer) mustEmbedUnimplementedAppControlServer() {}
func (UnimplementedAppControlServer) testEmbeddedByValue()                    {}

// UnsafeAppControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AppControlServer will
// result in compilation errors.
type UnsafeAppControlServer interface {
	mustEmbedUnimplementedAppControlServer()
}

func RegisterAppControlServer(s grpc.ServiceRegistrar, srv AppControlServer) {
	// If the following call pancis, it indicates UnimplementedAppControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AppControl_ServiceDesc, srv)
}

func _AppControl_SetVKCookies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetVKCookiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppControlServer).SetVKCookies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppControl_SetVKCookies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppControlServer).SetVKCookies(ctx, req.(*SetVKCookiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppControl_GetVKCookies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVKCookiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppControlServer).GetVKCookies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppControl_GetVKCookies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppControlServer).GetVKCookies(ctx, req.(*GetVKCookiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppControl_Provision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProvisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppControlServer).Provision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppControl_Provision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppControlServer).Provision(ctx, req.(*ProvisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AppControl_ServiceDesc is the grpc.ServiceDesc for AppControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AppControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vkturn.appcontrol.v1.AppControl",
	HandlerType: (*AppControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetVKCookies",
			Handler:    _AppControl_SetVKCookies_Handler,
		},
		{
			MethodName: "GetVKCookies",
			Handler:    _AppControl_GetVKCookies_Handler,
		},
		{
			MethodName: "Provision",
			Handler:    _AppControl_Provision_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/appcontrol.proto",
}
