// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/appcontrol.proto

// AppControl is the LOCAL IPC between the WINGS V host app and the embedded
// vk-turn-proxy client (libclient.so), served over a unix domain socket. It
// replaces the older stdin/stdout/cookie-file channels with a typed contract:
// the app pushes VK webview cookies in, and pulls the provisioned WireGuard
// config out.

package appcontrolpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetVKCookiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cookies       string                 `protobuf:"bytes,1,opt,name=cookies,proto3" json:"cookies,omitempty"`
	UserAgent     string                 `protobuf:"bytes,2,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetVKCookiesRequest) Reset() {
	*x = SetVKCookiesRequest{}
	mi := &file_proto_appcontrol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetVKCookiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetVKCookiesRequest) ProtoMessage() {}

func (x *SetVKCookiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appcontrol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetVKCookiesRequest.ProtoReflect.Descriptor instead.
func (*SetVKCookiesRequest) Descriptor() ([]byte, []int) {
	return file_proto_appcontrol_proto_rawDescGZIP(), []int{0}
}

func (x *SetVKCookiesRequest) GetCookies() string {
	if x != nil {
		return x.Cookies
	}
	return ""
}

func (x *SetVKCookiesRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

type SetVKCookiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetVKCookiesResponse) Reset() {
	*x = SetVKCookiesResponse{}
	mi := &file_proto_appcontrol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetVKCookiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetVKCookiesResponse) ProtoMessage() {}

func (x *SetVKCookiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appcontrol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetVKCookiesResponse.ProtoReflect.Descriptor instead.
func (*SetVKCookiesResponse) Descriptor() ([]byte, []int) {
	return file_proto_appcontrol_proto_rawDescGZIP(), []int{1}
}

type GetVKCookiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVKCookiesRequest) Reset() {
	*x = GetVKCookiesRequest{}
	mi := &file_proto_appcontrol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVKCookiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVKCookiesRequest) ProtoMessage() {}

func (x *GetVKCookiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appcontrol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVKCookiesRequest.ProtoReflect.Descriptor instead.
func (*GetVKCookiesRequest) Descriptor() ([]byte, []int) {
	return file_proto_appcontrol_proto_rawDescGZIP(), []int{2}
}

type GetVKCookiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cookies       string                 `protobuf:"bytes,1,opt,name=cookies,proto3" json:"cookies,omitempty"`
	UserAgent     string                 `protobuf:"bytes,2,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVKCookiesResponse) Reset() {
	*x = GetVKCookiesResponse{}
	mi := &file_proto_appcontrol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVKCookiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVKCookiesResponse) ProtoMessage() {}

func (x *GetVKCookiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appcontrol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVKCookiesResponse.ProtoReflect.Descriptor instead.
func (*GetVKCookiesResponse) Descriptor() ([]byte, []int) {
	return file_proto_appcontrol_proto_rawDescGZIP(), []int{3}
}

func (x *GetVKCookiesResponse) GetCookies() string {
	if x != nil {
		return x.Cookies
	}
	return ""
}

func (x *GetVKCookiesResponse) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

type ProvisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Token         []byte                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Hwid          string                 `protobuf:"bytes,3,opt,name=hwid,proto3" json:"hwid,omitempty"`
	LocalPort     uint32                 `protobuf:"varint,4,opt,name=local_port,json=localPort,proto3" json:"local_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionRequest) Reset() {
	*x = ProvisionRequest{}
	mi := &file_proto_appcontrol_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionRequest) ProtoMessage() {}

func (x *ProvisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appcontrol_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionRequest.ProtoReflect.Descriptor instead.
func (*ProvisionRequest) Descriptor() ([]byte, []int) {
	return file_proto_appcontrol_proto_rawDescGZIP(), []int{4}
}

func (x *ProvisionRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ProvisionRequest) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *ProvisionRequest) GetHwid() string {
	if x != nil {
		return x.Hwid
	}
	return ""
}

func (x *ProvisionRequest) GetLocalPort() uint32 {
	if x != nil {
		return x.LocalPort
	}
	return 0
}

type ProvisionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wg            *WireguardConfig       `protobuf:"bytes,1,opt,name=wg,proto3" json:"wg,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionResponse) Reset() {
	*x = ProvisionResponse{}
	mi := &file_proto_appcontrol_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionResponse) ProtoMessage() {}

func (x *ProvisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appcontrol_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionResponse.ProtoReflect.Descriptor instead.
func (*ProvisionResponse) Descriptor() ([]byte, []int) {
	return file_proto_appcontrol_proto_rawDescGZIP(), []int{5}
}

func (x *ProvisionResponse) GetWg() *WireguardConfig {
	if x != nil {
		return x.Wg
	}
	return nil
}

func (x *ProvisionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type WireguardConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PrivateKey      string                 `protobuf:"bytes,1,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	PublicKey       string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Address         string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	ServerPublicKey string                 `protobuf:"bytes,4,opt,name=server_public_key,json=serverPublicKey,proto3" json:"server_public_key,omitempty"`
	AllowedIps      string                 `protobuf:"bytes,5,opt,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`
	Mtu             uint32                 `protobuf:"varint,6,opt,name=mtu,proto3" json:"mtu,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WireguardConfig) Reset() {
	*x = WireguardConfig{}
	mi := &file_proto_appcontrol_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireguardConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireguardConfig) ProtoMessage() {}

func (x *WireguardConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appcontrol_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireguardConfig.ProtoReflect.Descriptor instead.
func (*WireguardConfig) Descriptor() ([]byte, []int) {
	return file_proto_appcontrol_proto_rawDescGZIP(), []int{6}
}

func (x *WireguardConfig) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *WireguardConfig) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *WireguardConfig) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *WireguardConfig) GetServerPublicKey() string {
	if x != nil {
		return x.ServerPublicKey
	}
	return ""
}

func (x *WireguardConfig) GetAllowedIps() string {
	if x != nil {
		return x.AllowedIps
	}
	return ""
}

func (x *WireguardConfig) GetMtu() uint32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

var File_proto_appcontrol_proto protoreflect.FileDescriptor

const file_proto_appcontrol_proto_rawDesc = "" +
	"\n" +
	"\x16proto/appcontrol.proto\x12\x14vkturn.appcontrol.v1\"N\n" +
	"\x13SetVKCookiesRequest\x12\x18\n" +
	"\acookies\x18\x01 \x01(\tR\acookies\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x02 \x01(\tR\tuserAgent\"\x16\n" +
	"\x14SetVKCookiesResponse\"\x15\n" +
	"\x13GetVKCookiesRequest\"O\n" +
	"\x14GetVKCookiesResponse\x12\x18\n" +
	"\acookies\x18\x01 \x01(\tR\acookies\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x02 \x01(\tR\tuserAgent\"x\n" +
	"\x10ProvisionRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\fR\x05token\x12\x12\n" +
	"\x04hwid\x18\x03 \x01(\tR\x04hwid\x12\x1d\n" +
	"\n" +
	"local_port\x18\x04 \x01(\rR\tlocalPort\"`\n" +
	"\x11ProvisionResponse\x125\n" +
	"\x02wg\x18\x01 \x01(\v2%.vkturn.appcontrol.v1.WireguardConfigR\x02wg\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xca\x01\n" +
	"\x0fWireguardConfig\x12\x1f\n" +
	"\vprivate_key\x18\x01 \x01(\tR\n" +
	"privateKey\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12*\n" +
	"\x11server_public_key\x18\x04 \x01(\tR\x0fserverPublicKey\x12\x1f\n" +
	"\vallowed_ips\x18\x05 \x01(\tR\n" +
	"allowedIps\x12\x10\n" +
	"\x03mtu\x18\x06 \x01(\rR\x03mtu2\xb8\x02\n" +
	"\n" +
	"AppControl\x12e\n" +
	"\fSetVKCookies\x12).vkturn.appcontrol.v1.SetVKCookiesRequest\x1a*.vkturn.appcontrol.v1.SetVKCookiesResponse\x12e\n" +
	"\fGetVKCookies\x12).vkturn.appcontrol.v1.GetVKCookiesRequest\x1a*.vkturn.appcontrol.v1.GetVKCookiesResponse\x12\\\n" +
	"\tProvision\x12&.vkturn.appcontrol.v1.ProvisionRequest\x1a'.vkturn.appcontrol.v1.ProvisionResponseB=Z;github.com/cacggghp/vk-turn-proxy/appcontrolpb;appcontrolpbb\x06proto3"

var (
	file_proto_appcontrol_proto_rawDescOnce sync.Once
	file_proto_appcontrol_proto_rawDescData []byte
)

func file_proto_appcontrol_proto_rawDescGZIP() []byte {
	file_proto_appcontrol_proto_rawDescOnce.Do(func() {
		file_proto_appcontrol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_appcontrol_proto_rawDesc), len(file_proto_appcontrol_proto_rawDesc)))
	})
	return file_proto_appcontrol_proto_rawDescData
}

var file_proto_appcontrol_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_appcontrol_proto_goTypes = []any{
	(*SetVKCookiesRequest)(nil),  // 0: vkturn.appcontrol.v1.SetVKCookiesRequest
	(*SetVKCookiesResponse)(nil), // 1: vkturn.appcontrol.v1.SetVKCookiesResponse
	(*GetVKCookiesRequest)(nil),  // 2: vkturn.appcontrol.v1.GetVKCookiesRequest
	(*GetVKCookiesResponse)(nil), // 3: vkturn.appcontrol.v1.GetVKCookiesResponse
	(*ProvisionRequest)(nil),     // 4: vkturn.appcontrol.v1.ProvisionRequest
	(*ProvisionResponse)(nil),    // 5: vkturn.appcontrol.v1.ProvisionResponse
	(*WireguardConfig)(nil),      // 6: vkturn.appcontrol.v1.WireguardConfig
}
var file_proto_appcontrol_proto_depIdxs = []int32{
	6, // 0: vkturn.appcontrol.v1.ProvisionResponse.wg:type_name -> vkturn.appcontrol.v1.WireguardConfig
	0, // 1: vkturn.appcontrol.v1.AppControl.SetVKCookies:input_type -> vkturn.appcontrol.v1.SetVKCookiesRequest
	2, // 2: vkturn.appcontrol.v1.AppControl.GetVKCookies:input_type -> vkturn.appcontrol.v1.GetVKCookiesRequest
	4, // 3: vkturn.appcontrol.v1.AppControl.Provision:input_type -> vkturn.appcontrol.v1.ProvisionRequest
	1, // 4: vkturn.appcontrol.v1.AppControl.SetVKCookies:output_type -> vkturn.appcontrol.v1.SetVKCookiesResponse
	3, // 5: vkturn.appcontrol.v1.AppControl.GetVKCookies:output_type -> vkturn.appcontrol.v1.GetVKCookiesResponse
	5, // 6: vkturn.appcontrol.v1.AppControl.Provision:output_type -> vkturn.appcontrol.v1.ProvisionResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_appcontrol_proto_init() }
func file_proto_appcontrol_proto_init() {
	if File_proto_appcontrol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_appcontrol_proto_rawDesc), len(file_proto_appcontrol_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_appcontrol_proto_goTypes,
		DependencyIndexes: file_proto_appcontrol_proto_depIdxs,
		MessageInfos:      file_proto_appcontrol_proto_msgTypes,
	}.Build()
	File_proto_appcontrol_proto = out.File
	file_proto_appcontrol_proto_goTypes = nil
	file_proto_appcontrol_proto_depIdxs = nil
}
