// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/session.proto

package sessionproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientHelloType int32

const (
	ClientHelloType_CLIENT_HELLO_TYPE_UNSPECIFIED ClientHelloType = 0
	ClientHelloType_CLIENT_HELLO_TYPE_PROBE       ClientHelloType = 1
	ClientHelloType_CLIENT_HELLO_TYPE_SESSION     ClientHelloType = 2
)

// Enum value maps for ClientHelloType.
var (
	ClientHelloType_name = map[int32]string{
		0: "CLIENT_HELLO_TYPE_UNSPECIFIED",
		1: "CLIENT_HELLO_TYPE_PROBE",
		2: "CLIENT_HELLO_TYPE_SESSION",
	}
	ClientHelloType_value = map[string]int32{
		"CLIENT_HELLO_TYPE_UNSPECIFIED": 0,
		"CLIENT_HELLO_TYPE_PROBE":       1,
		"CLIENT_HELLO_TYPE_SESSION":     2,
	}
)

func (x ClientHelloType) Enum() *ClientHelloType {
	p := new(ClientHelloType)
	*p = x
	return p
}

func (x ClientHelloType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientHelloType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_session_proto_enumTypes[0].Descriptor()
}

func (ClientHelloType) Type() protoreflect.EnumType {
	return &file_proto_session_proto_enumTypes[0]
}

func (x ClientHelloType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientHelloType.Descriptor instead.
func (ClientHelloType) EnumDescriptor() ([]byte, []int) {
	return file_proto_session_proto_rawDescGZIP(), []int{0}
}

type TransportMode int32

const (
	TransportMode_TRANSPORT_MODE_UNSPECIFIED TransportMode = 0
	TransportMode_TRANSPORT_MODE_DATAGRAM    TransportMode = 1
	TransportMode_TRANSPORT_MODE_TCP         TransportMode = 2
)

// Enum value maps for TransportMode.
var (
	TransportMode_name = map[int32]string{
		0: "TRANSPORT_MODE_UNSPECIFIED",
		1: "TRANSPORT_MODE_DATAGRAM",
		2: "TRANSPORT_MODE_TCP",
	}
	TransportMode_value = map[string]int32{
		"TRANSPORT_MODE_UNSPECIFIED": 0,
		"TRANSPORT_MODE_DATAGRAM":    1,
		"TRANSPORT_MODE_TCP":         2,
	}
)

func (x TransportMode) Enum() *TransportMode {
	p := new(TransportMode)
	*p = x
	return p
}

func (x TransportMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransportMode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_session_proto_enumTypes[1].Descriptor()
}

func (TransportMode) Type() protoreflect.EnumType {
	return &file_proto_session_proto_enumTypes[1]
}

func (x TransportMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransportMode.Descriptor instead.
func (TransportMode) EnumDescriptor() ([]byte, []int) {
	return file_proto_session_proto_rawDescGZIP(), []int{1}
}

type ClientHello struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Version             uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Type                ClientHelloType        `protobuf:"varint,2,opt,name=type,proto3,enum=sessionproto.ClientHelloType" json:"type,omitempty"`
	SessionId           []byte                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	StreamId            uint32                 `protobuf:"varint,4,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	RequestedTransport  TransportMode          `protobuf:"varint,5,opt,name=requested_transport,json=requestedTransport,proto3,enum=sessionproto.TransportMode" json:"requested_transport,omitempty"`
	SupportedTransports []TransportMode        `protobuf:"varint,6,rep,packed,name=supported_transports,json=supportedTransports,proto3,enum=sessionproto.TransportMode" json:"supported_transports,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ClientHello) Reset() {
	*x = ClientHello{}
	mi := &file_proto_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientHello) ProtoMessage() {}

func (x *ClientHello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientHello.ProtoReflect.Descriptor instead.
func (*ClientHello) Descriptor() ([]byte, []int) {
	return file_proto_session_proto_rawDescGZIP(), []int{0}
}

func (x *ClientHello) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ClientHello) GetType() ClientHelloType {
	if x != nil {
		return x.Type
	}
	return ClientHelloType_CLIENT_HELLO_TYPE_UNSPECIFIED
}

func (x *ClientHello) GetSessionId() []byte {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *ClientHello) GetStreamId() uint32 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

func (x *ClientHello) GetRequestedTransport() TransportMode {
	if x != nil {
		return x.RequestedTransport
	}
	return TransportMode_TRANSPORT_MODE_UNSPECIFIED
}

func (x *ClientHello) GetSupportedTransports() []TransportMode {
	if x != nil {
		return x.SupportedTransports
	}
	return nil
}

type ServerHello struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Version                   uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	MuxSupported              bool                   `protobuf:"varint,2,opt,name=mux_supported,json=muxSupported,proto3" json:"mux_supported,omitempty"`
	Error                     string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	ControlHeartbeatSupported bool                   `protobuf:"varint,4,opt,name=control_heartbeat_supported,json=controlHeartbeatSupported,proto3" json:"control_heartbeat_supported,omitempty"`
	SelectedTransport         TransportMode          `protobuf:"varint,5,opt,name=selected_transport,json=selectedTransport,proto3,enum=sessionproto.TransportMode" json:"selected_transport,omitempty"`
	SupportedTransports       []TransportMode        `protobuf:"varint,6,rep,packed,name=supported_transports,json=supportedTransports,proto3,enum=sessionproto.TransportMode" json:"supported_transports,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ServerHello) Reset() {
	*x = ServerHello{}
	mi := &file_proto_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerHello) ProtoMessage() {}

func (x *ServerHello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerHello.ProtoReflect.Descriptor instead.
func (*ServerHello) Descriptor() ([]byte, []int) {
	return file_proto_session_proto_rawDescGZIP(), []int{1}
}

func (x *ServerHello) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ServerHello) GetMuxSupported() bool {
	if x != nil {
		return x.MuxSupported
	}
	return false
}

func (x *ServerHello) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ServerHello) GetControlHeartbeatSupported() bool {
	if x != nil {
		return x.ControlHeartbeatSupported
	}
	return false
}

func (x *ServerHello) GetSelectedTransport() TransportMode {
	if x != nil {
		return x.SelectedTransport
	}
	return TransportMode_TRANSPORT_MODE_UNSPECIFIED
}

func (x *ServerHello) GetSupportedTransports() []TransportMode {
	if x != nil {
		return x.SupportedTransports
	}
	return nil
}

type Heartbeat struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Version          uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	WallClockMs      int64                  `protobuf:"varint,2,opt,name=wall_clock_ms,json=wallClockMs,proto3" json:"wall_clock_ms,omitempty"`
	ActiveStreams    uint32                 `protobuf:"varint,3,opt,name=active_streams,json=activeStreams,proto3" json:"active_streams,omitempty"`
	Online           bool                   `protobuf:"varint,4,opt,name=online,proto3" json:"online,omitempty"`
	ProtoFingerprint string                 `protobuf:"bytes,5,opt,name=proto_fingerprint,json=protoFingerprint,proto3" json:"proto_fingerprint,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_session_proto_rawDescGZIP(), []int{2}
}

func (x *Heartbeat) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Heartbeat) GetWallClockMs() int64 {
	if x != nil {
		return x.WallClockMs
	}
	return 0
}

func (x *Heartbeat) GetActiveStreams() uint32 {
	if x != nil {
		return x.ActiveStreams
	}
	return 0
}

func (x *Heartbeat) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *Heartbeat) GetProtoFingerprint() string {
	if x != nil {
		return x.ProtoFingerprint
	}
	return ""
}

var File_proto_session_proto protoreflect.FileDescriptor

const file_proto_session_proto_rawDesc = "" +
	"\n" +
	"\x13proto/session.proto\x12\fsessionproto\"\xb4\x02\n" +
	"\vClientHello\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x121\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1d.sessionproto.ClientHelloTypeR\x04type\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\fR\tsessionId\x12\x1b\n" +
	"\tstream_id\x18\x04 \x01(\rR\bstreamId\x12L\n" +
	"\x13requested_transport\x18\x05 \x01(\x0e2\x1b.sessionproto.TransportModeR\x12requestedTransport\x12N\n" +
	"\x14supported_transports\x18\x06 \x03(\x0e2\x1b.sessionproto.TransportModeR\x13supportedTransports\"\xbe\x02\n" +
	"\vServerHello\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12#\n" +
	"\rmux_supported\x18\x02 \x01(\bR\fmuxSupported\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12>\n" +
	"\x1bcontrol_heartbeat_supported\x18\x04 \x01(\bR\x19controlHeartbeatSupported\x12J\n" +
	"\x12selected_transport\x18\x05 \x01(\x0e2\x1b.sessionproto.TransportModeR\x11selectedTransport\x12N\n" +
	"\x14supported_transports\x18\x06 \x03(\x0e2\x1b.sessionproto.TransportModeR\x13supportedTransports\"\xb5\x01\n" +
	"\tHeartbeat\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\"\n" +
	"\rwall_clock_ms\x18\x02 \x01(\x03R\vwallClockMs\x12%\n" +
	"\x0eactive_streams\x18\x03 \x01(\rR\ractiveStreams\x12\x16\n" +
	"\x06online\x18\x04 \x01(\bR\x06online\x12+\n" +
	"\x11proto_fingerprint\x18\x05 \x01(\tR\x10protoFingerprint*p\n" +
	"\x0fClientHelloType\x12!\n" +
	"\x1dCLIENT_HELLO_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17CLIENT_HELLO_TYPE_PROBE\x10\x01\x12\x1d\n" +
	"\x19CLIENT_HELLO_TYPE_SESSION\x10\x02*d\n" +
	"\rTransportMode\x12\x1e\n" +
	"\x1aTRANSPORT_MODE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17TRANSPORT_MODE_DATAGRAM\x10\x01\x12\x16\n" +
	"\x12TRANSPORT_MODE_TCP\x10\x02B=Z;github.com/cacggghp/vk-turn-proxy/sessionproto;sessionprotob\x06proto3"

var (
	file_proto_session_proto_rawDescOnce sync.Once
	file_proto_session_proto_rawDescData []byte
)

func file_proto_session_proto_rawDescGZIP() []byte {
	file_proto_session_proto_rawDescOnce.Do(func() {
		file_proto_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_session_proto_rawDesc), len(file_proto_session_proto_rawDesc)))
	})
	return file_proto_session_proto_rawDescData
}

var file_proto_session_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_session_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_session_proto_goTypes = []any{
	(ClientHelloType)(0), // 0: sessionproto.ClientHelloType
	(TransportMode)(0),   // 1: sessionproto.TransportMode
	(*ClientHello)(nil),  // 2: sessionproto.ClientHello
	(*ServerHello)(nil),  // 3: sessionproto.ServerHello
	(*Heartbeat)(nil),    // 4: sessionproto.Heartbeat
}
var file_proto_session_proto_depIdxs = []int32{
	0, // 0: sessionproto.ClientHello.type:type_name -> sessionproto.ClientHelloType
	1, // 1: sessionproto.ClientHello.requested_transport:type_name -> sessionproto.TransportMode
	1, // 2: sessionproto.ClientHello.supported_transports:type_name -> sessionproto.TransportMode
	1, // 3: sessionproto.ServerHello.selected_transport:type_name -> sessionproto.TransportMode
	1, // 4: sessionproto.ServerHello.supported_transports:type_name -> sessionproto.TransportMode
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_session_proto_init() }
func file_proto_session_proto_init() {
	if File_proto_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_session_proto_rawDesc), len(file_proto_session_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_session_proto_goTypes,
		DependencyIndexes: file_proto_session_proto_depIdxs,
		EnumInfos:         file_proto_session_proto_enumTypes,
		MessageInfos:      file_proto_session_proto_msgTypes,
	}.Build()
	File_proto_session_proto = out.File
	file_proto_session_proto_goTypes = nil
	file_proto_session_proto_depIdxs = nil
}
