// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/session.proto

package sessionproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientHelloType int32

const (
	ClientHelloType_CLIENT_HELLO_TYPE_UNSPECIFIED ClientHelloType = 0
	ClientHelloType_CLIENT_HELLO_TYPE_PROBE       ClientHelloType = 1
	ClientHelloType_CLIENT_HELLO_TYPE_SESSION     ClientHelloType = 2
)

// Enum value maps for ClientHelloType.
var (
	ClientHelloType_name = map[int32]string{
		0: "CLIENT_HELLO_TYPE_UNSPECIFIED",
		1: "CLIENT_HELLO_TYPE_PROBE",
		2: "CLIENT_HELLO_TYPE_SESSION",
	}
	ClientHelloType_value = map[string]int32{
		"CLIENT_HELLO_TYPE_UNSPECIFIED": 0,
		"CLIENT_HELLO_TYPE_PROBE":       1,
		"CLIENT_HELLO_TYPE_SESSION":     2,
	}
)

func (x ClientHelloType) Enum() *ClientHelloType {
	p := new(ClientHelloType)
	*p = x
	return p
}

func (x ClientHelloType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientHelloType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_session_proto_enumTypes[0].Descriptor()
}

func (ClientHelloType) Type() protoreflect.EnumType {
	return &file_proto_session_proto_enumTypes[0]
}

func (x ClientHelloType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientHelloType.Descriptor instead.
func (ClientHelloType) EnumDescriptor() ([]byte, []int) {
	return file_proto_session_proto_rawDescGZIP(), []int{0}
}

type ClientHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Type          ClientHelloType        `protobuf:"varint,2,opt,name=type,proto3,enum=sessionproto.ClientHelloType" json:"type,omitempty"`
	SessionId     []byte                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	StreamId      uint32                 `protobuf:"varint,4,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientHello) Reset() {
	*x = ClientHello{}
	mi := &file_proto_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientHello) ProtoMessage() {}

func (x *ClientHello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientHello.ProtoReflect.Descriptor instead.
func (*ClientHello) Descriptor() ([]byte, []int) {
	return file_proto_session_proto_rawDescGZIP(), []int{0}
}

func (x *ClientHello) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ClientHello) GetType() ClientHelloType {
	if x != nil {
		return x.Type
	}
	return ClientHelloType_CLIENT_HELLO_TYPE_UNSPECIFIED
}

func (x *ClientHello) GetSessionId() []byte {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *ClientHello) GetStreamId() uint32 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

type ServerHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	MuxSupported  bool                   `protobuf:"varint,2,opt,name=mux_supported,json=muxSupported,proto3" json:"mux_supported,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerHello) Reset() {
	*x = ServerHello{}
	mi := &file_proto_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerHello) ProtoMessage() {}

func (x *ServerHello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerHello.ProtoReflect.Descriptor instead.
func (*ServerHello) Descriptor() ([]byte, []int) {
	return file_proto_session_proto_rawDescGZIP(), []int{1}
}

func (x *ServerHello) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ServerHello) GetMuxSupported() bool {
	if x != nil {
		return x.MuxSupported
	}
	return false
}

func (x *ServerHello) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_session_proto protoreflect.FileDescriptor

const file_proto_session_proto_rawDesc = "" +
	"\n" +
	"\x13proto/session.proto\x12\fsessionproto\"\x96\x01\n" +
	"\vClientHello\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x121\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1d.sessionproto.ClientHelloTypeR\x04type\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\fR\tsessionId\x12\x1b\n" +
	"\tstream_id\x18\x04 \x01(\rR\bstreamId\"b\n" +
	"\vServerHello\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12#\n" +
	"\rmux_supported\x18\x02 \x01(\bR\fmuxSupported\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error*p\n" +
	"\x0fClientHelloType\x12!\n" +
	"\x1dCLIENT_HELLO_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17CLIENT_HELLO_TYPE_PROBE\x10\x01\x12\x1d\n" +
	"\x19CLIENT_HELLO_TYPE_SESSION\x10\x02B=Z;github.com/cacggghp/vk-turn-proxy/sessionproto;sessionprotob\x06proto3"

var (
	file_proto_session_proto_rawDescOnce sync.Once
	file_proto_session_proto_rawDescData []byte
)

func file_proto_session_proto_rawDescGZIP() []byte {
	file_proto_session_proto_rawDescOnce.Do(func() {
		file_proto_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_session_proto_rawDesc), len(file_proto_session_proto_rawDesc)))
	})
	return file_proto_session_proto_rawDescData
}

var file_proto_session_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_session_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_session_proto_goTypes = []any{
	(ClientHelloType)(0), // 0: sessionproto.ClientHelloType
	(*ClientHello)(nil),  // 1: sessionproto.ClientHello
	(*ServerHello)(nil),  // 2: sessionproto.ServerHello
}
var file_proto_session_proto_depIdxs = []int32{
	0, // 0: sessionproto.ClientHello.type:type_name -> sessionproto.ClientHelloType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_session_proto_init() }
func file_proto_session_proto_init() {
	if File_proto_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_session_proto_rawDesc), len(file_proto_session_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_session_proto_goTypes,
		DependencyIndexes: file_proto_session_proto_depIdxs,
		EnumInfos:         file_proto_session_proto_enumTypes,
		MessageInfos:      file_proto_session_proto_msgTypes,
	}.Build()
	File_proto_session_proto = out.File
	file_proto_session_proto_goTypes = nil
	file_proto_session_proto_depIdxs = nil
}
